# -- [Application Configuration] -- #
spring.restdocs.version=3.0.2
server.servlet.context-path=/code-guard
server.port=8080
spring.application.name=CodeGuard

# -- [JPA Configuration] -- #
spring.jpa.hibernate.ddl-auto=none

# -- [Swagger] -- #
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=api/index.html
springdoc.swagger-ui.enabled=true

# -- [BBDD Configuration] -- #
#BBDD Users
spring.datasource.users.jdbc-url=jdbc:mysql://mysql-codeguard.cjsgaq6kqh3v.eu-west-3.rds.amazonaws.com:3306/users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.users.username=admin
spring.datasource.users.password=mqFHhuLIW6ReGbZ4rYBJ

#BBDD DeletedUsers
spring.datasource.deleted-users.jdbc-url=jdbc:mysql://mysql-codeguard.cjsgaq6kqh3v.eu-west-3.rds.amazonaws.com:3306/deletedUsers?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.deleted-users.username=admin
spring.datasource.deleted-users.password=mqFHhuLIW6ReGbZ4rYBJ

#BBDD Passwords
spring.datasource.passwords.jdbc-url=jdbc:mysql://mysql-codeguard.cjsgaq6kqh3v.eu-west-3.rds.amazonaws.com:3306/passwords?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.passwords.username=admin
spring.datasource.passwords.password=mqFHhuLIW6ReGbZ4rYBJ

#BBDD Exercises
spring.datasource.exercises.jdbc-url=jdbc:mysql://mysql-codeguard.cjsgaq6kqh3v.eu-west-3.rds.amazonaws.com:3306/exercises?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.exercises.username=admin
spring.datasource.exercises.password=mqFHhuLIW6ReGbZ4rYBJ

# -- [JWT Configuration] -- #
jwt.secret-key=87a5bd4fba5c0070fdf6a6cafaaa7de3fb3617a364e68e63b816a81a6198e36d196c155bf0ff8f4be31750f9d520e0d0dc2bfb8ec9da78cd8464281704ceaf6eb616454c5548259b29272096a29d2ccea15a901ea8839a348512f06a396ed6fddf694de63da5c82a172eb793669d181fa00d9f3dd357541c4e17918180674569711eabad4bc9f3bd733f8eacb5cf2e347cfa1775a7c039c91814a1d941f1a475b343ece78bb879b7cb9f65d7be6fc305a0c24153f61de7c2d524de4d54c5fabf769d04b3788d5f5a9c53b87f0ad653821edc3207b302ab815171df3fccd141871fcf87eaa66695409e8f7eb3107088da9f187809bf64c886688ee1b8d43a355e